- app/sdil/controllers/LitreageController.scala
- app/sdil/controllers/SDILController.scala
- app/sdil/controllers/VerifyController.scala
- app/views/softdrinksindustrylevy/helpers/declaration_details_table_row.scala.html
- app/views/softdrinksindustrylevy/register/declaration.scala.html
- conf/app.routes
- conf/messages
- test/sdil/controllers/SDILControllerSpec.scala
- test/sdil/controllers/VerifyControllerSpec.scala
> added the declaration page with some dummy data

- app/sdil/controllers/CopackedController.scala
- app/sdil/controllers/ImportController.scala
- app/sdil/controllers/PackageCopackSmallController.scala
- app/sdil/controllers/SDILController.scala
- app/sdil/controllers/package.scala
- app/views/softdrinksindustrylevy/register/copacked.scala.html
- app/views/softdrinksindustrylevy/register/imports.scala.html
- app/views/softdrinksindustrylevy/register/package_copack_small.scala.html
- conf/app.routes
- conf/messages
- test/sdil/controllers/CopackedControllerSpec.scala
- test/sdil/controllers/ImportControllerSpec.scala
- test/sdil/controllers/PackageCopackSmallControllerSpec.scala
- test/sdil/controllers/SDILControllerSpec.scala
- test/sdil/controllers/package.scala
3 binary pages added:
- Package Copack Small
- Import
- Copacked
Pages route to their correct pages based on their true/false value.
> Added 3 Binary Pages

- app/views/softdrinksindustrylevy/register/package_copack_small.scala.html
Ensure it matches prototype after QA review
> Move Save and Continue button to match the Prototype

- app/sdil/models/Pages.scala
- test/sdil/controllers/LitreageControllerSpec.scala
- test/sdil/controllers/PackageControllerSpec.scala
Matches the flow diagram here https://confluence.tools.tax.service.gov.uk/display/SDIL/01+Registration
> SDIL-919 Page Routing forwards and backwards

- app/sdil/connectors/SoftDrinksIndustryLevyConnector.scala
- app/sdil/controllers/VerifyController.scala
- test/sdil/controllers/VerifyControllerSpec.scala
> Sdil 937 call enrolment not pending check

- app/sdil/config/RoutesWiring.scala
- app/sdil/config/frontendAppConfig.scala
- app/sdil/controllers/SignoutController.scala
- app/views/govuk_wrapper.scala.html
- conf/app.routes
- conf/messages
Added new controller with route
> Added sign out link and required message

- app/sdil/connectors/TestConnector.scala
- app/sdil/controllers/test/TestingController.scala
- conf/testOnlyDoNotUseInAppConf.routes
Please review and merge assuming the backend merge with the same name has happened.
> Sdil 972 part two

- app/views/softdrinksindustrylevy/register/declaration.scala.html
- app/views/softdrinksindustrylevy/register/organisation_type.scala.html
- app/views/softdrinksindustrylevy/register/packagePage.scala.html
- app/views/softdrinksindustrylevy/register/productionSite.scala.html
- app/views/softdrinksindustrylevy/register/radio_button.scala.html
- app/views/softdrinksindustrylevy/register/secondaryWarehouse.scala.html
- app/views/softdrinksindustrylevy/register/verify.scala.html
- conf/messages
> restructure of content

- app/views/softdrinksindustrylevy/register/declaration.scala.html
> only display exemption on declaration if relevant

- app/sdil/actions/AuthorisedAction.scala
- app/sdil/config/RoutesWiring.scala
- app/sdil/controllers/AlreadyRegisteredController.scala
- app/sdil/controllers/VerifyController.scala
- app/views/softdrinksindustrylevy/errors/already_registered.scala.html
- app/views/softdrinksindustrylevy/register/verify.scala.html
- conf/app.routes
- conf/messages
- test/sdil/actions/AuthorisedActionSpec.scala
> Sdil 1028 already enrolled by someone else

- app/sdil/controllers/RegistrationTypeController.scala
- app/sdil/models/RegistrationFormData.scala
- app/views/softdrinksindustrylevy/register/declaration.scala.html
> removed duplicated logic and fixed small prod exemption declaration

- app/sdil/controllers/DeclarationController.scala
- test/sdil/controllers/DeclarationControllerSpec.scala
> Sdil 1114 hide declaration from non liable user

- app/sdil/models/Pages.scala
- test/sdil/controllers/ContactDetailsControllerSpec.scala
- test/sdil/controllers/StartDateControllerSpec.scala
- test/sdil/controllers/WarehouseControllerSpec.scala
> Sdil 1135 routing

- app/views/softdrinksindustrylevy/errors/already_registered.scala.html
- app/views/softdrinksindustrylevy/register/complete.scala.html
- app/views/softdrinksindustrylevy/register/smallProducerConfirm.scala.html
- conf/messages
- test/sdil/controllers/CompleteControllerSpec.scala
> tweaks from run through

- app/views/govuk_wrapper.scala.html
- app/views/softdrinksindustrylevy/service_page.scala.html
- conf/messages
- test/sdil/controllers/ServicePageControllerSpec.scala
Changed heading on service page
Added test to check correct heading is used on service page
> Changed headings on registration pages

- app/sdil/controllers/ProductionSiteController.scala
- app/views/softdrinksindustrylevy/helpers/addressCheckbox.scala.html
- app/views/softdrinksindustrylevy/register/productionSite.scala.html
- app/views/softdrinksindustrylevy/register/secondaryWarehouse.scala.html
checkbox behaviour on production site and secondary warehouse address pages
> Fix SDIL-1192

- app/views/softdrinksindustrylevy/helpers/declaration_details_litres.scala.html
- app/views/softdrinksindustrylevy/register/complete.scala.html
Change buttons have visually hidden explanations for screen readers.
> Formatted time to display am or pm in lower case with space removed.

- app/sdil/forms/FormHelpers.scala
- app/views/softdrinksindustrylevy/register/litreagePage.scala.html
- public/javascripts/application.js
Changed litreage fields to be text type
Added volume class to prevent all other text fields being affected
> Added js which adds commas to litreage fields when numbers are entered

- project/FrontendBuild.scala
- public/javascripts/application.js
- public/javascripts/details.polyfill.js
> IE details polyfill

- conf/messages
> message on package-copack-vol

- app/views/softdrinksindustrylevy/helpers/businessDetails.scala.html
- app/views/softdrinksindustrylevy/helpers/declaration_table.scala.html
- app/views/softdrinksindustrylevy/helpers/details.scala.html
- app/views/softdrinksindustrylevy/register/produce_worldwide.scala.html
- app/views/softdrinksindustrylevy/register/productionSite.scala.html
- app/views/softdrinksindustrylevy/register/verify.scala.html
- conf/messages
- public/stylesheets/sdil.css
Fixed table on pending page
Increased width on check your answer tables
> Fixed up details tags with spacing

- app/sdil/controllers/StartDateController.scala
- test/sdil/controllers/StartDateControllerSpec.scala
> Small producer will no longer see the start date page

- app/views/softdrinksindustrylevy/helpers/declaration_table.scala.html
- conf/messages
- public/stylesheets/sdil.css
> fixes for declaration page mobile layout

- app/views/softdrinksindustrylevy/register/declaration.scala.html
> start date hidden from small producers on declaration page

- app/sdil/controllers/StartDateController.scala
- app/sdil/models/Pages.scala
- app/views/softdrinksindustrylevy/register/declaration.scala.html
- test/sdil/controllers/ContactDetailsControllerSpec.scala
- test/sdil/controllers/WarehouseControllerSpec.scala
> Sdil 1265 declaration page fix

- app/sdil/models/RegistrationFormData.scala
- test/sdil/controllers/ProductionSiteControllerSpec.scala
- test/sdil/controllers/StartDateControllerSpec.scala
> production sites page not shown unless you package for self or others

- app/views/softdrinksindustrylevy/register/litreagePage.scala.html
- app/views/softdrinksindustrylevy/register/produce_worldwide.scala.html
- app/views/softdrinksindustrylevy/register/registration_not_required.scala.html
- app/views/softdrinksindustrylevy/register/start_date.scala.html
- conf/application.conf
- conf/messages
> new content on do not register page

- app/views/softdrinksindustrylevy/register/declaration.scala.html
- conf/messages
> declaration copy changes

- app/sdil/config/RoutesWiring.scala
- app/sdil/controllers/ContactDetailsController.scala
- app/sdil/controllers/variation/ContactDetailsVariationController.scala
- app/sdil/models/variations/VariationData.scala
- app/views/softdrinksindustrylevy/register/contact_details.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary.scala.html
- conf/application.conf
- conf/variations.routes
- test/sdil/controllers/variation/ContactDetailsVariationControllerSpec.scala
- test/sdil/controllers/variation/package.scala
> Variations phat form

- app/sdil/actions/AuthorisedAction.scala
- app/sdil/connectors/SoftDrinksIndustryLevyConnector.scala
- app/views/softdrinksindustrylevy/service_page.scala.html
- conf/messages
Optimised imports
Removed warning in service page
> Removed unused items in case match

- app/sdil/models/variations/VariationData.scala
- app/views/softdrinksindustrylevy/variations/retrieve_summary.scala.html
- test/sdil/controllers/variation/VariationsControllerSpec.scala
> variation summary for voluntary reg

- app/views/softdrinksindustrylevy/helpers/details.scala.html
Remove role from details as per DAC report.
> Remove role from details tag

- app/sdil/controllers/variation/ProductionSiteVariationController.scala
- app/sdil/controllers/variation/SiteRef.scala
- app/sdil/controllers/variation/WarehouseVariationController.scala
- app/sdil/controllers/variation/models/Sites.scala
- app/sdil/forms/FormHelpers.scala
- app/sdil/models/variations/VariationData.scala
- app/views/softdrinksindustrylevy/variations/productionSiteWithRef.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary.scala.html
- app/views/softdrinksindustrylevy/variations/secondaryWarehouseWithRef.scala.html
- app/views/softdrinksindustrylevy/variations/siteRefCheckbox.scala.html
- test/sdil/controllers/DeclarationControllerSpec.scala
- test/sdil/controllers/ServicePageControllerSpec.scala
- test/sdil/controllers/variation/ProductionSiteVariationControllerSpec.scala
- test/sdil/controllers/variation/WarehouseVariationControllerSpec.scala
> Sdil 1438 add site ref

- app/views/softdrinksindustrylevy/variations/business_details.scala.html
> remove trading name from business details form template

- app/sdil/controllers/variation/ContactDetailsVariationController.scala
- app/views/softdrinksindustrylevy/variations/retrieve_summary_contact_details.scala.html
- conf/variations.routes
- test/sdil/controllers/variation/ContactDetailsVariationControllerSpec.scala
> new design for fat-form (activities)

- app/sdil/controllers/variation/ProductionSiteVariationController.scala
- app/views/softdrinksindustrylevy/variations/retrieve_summary_productionSites.scala.html
- conf/variations.routes
- test/sdil/controllers/variation/ProductionSiteVariationControllerSpec.scala
> new design for fat-form (packaging sites)

- app/sdil/controllers/variation/WarehouseVariationController.scala
- app/views/softdrinksindustrylevy/variations/retrieve_summary_secondaryWarehouse.scala.html
- conf/variations.routes
> new design for fat-form (warehouse sites)

- app/views/softdrinksindustrylevy/variations/business_details_summary.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary_contact_details.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary_productionSites.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary_secondaryWarehouse.scala.html
- conf/messages
> cancel buttons and no change links on summary pages

- app/sdil/controllers/variation/VariationsSummaryController.scala
- app/views/softdrinksindustrylevy/variations/confirmation.scala.html
- conf/messages
> confirmation page date, print and link to do more

- app/views/softdrinksindustrylevy/service_page.scala.html
- conf/application.conf
> Fixed structure of service page.

- app/sdil/controllers/variation/ContactDetailsVariationController.scala
- app/views/softdrinksindustrylevy/register/contact_details.scala.html
- app/views/softdrinksindustrylevy/variations/business_details.scala.html
- app/views/softdrinksindustrylevy/variations/business_details_summary.scala.html
- app/views/softdrinksindustrylevy/variations/confirmation.scala.html
- app/views/softdrinksindustrylevy/variations/productionSiteWithRef.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary_contact_details.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary_productionSites.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary_secondaryWarehouse.scala.html
- app/views/softdrinksindustrylevy/variations/secondaryWarehouseWithRef.scala.html
- app/views/softdrinksindustrylevy/variations/variations_summary.scala.html
- conf/messages
Added variation boolean for contact details since the template is reused
> Changed variation templates to use correct title

- app/views/softdrinksindustrylevy/helpers/details.scala.html
- public/stylesheets/sdil.css
Removed styling for details tag
> Changed details tag to include role of group

- app/sdil/controllers/variation/ContactDetailsVariationController.scala
- app/views/govuk_wrapper.scala.html
- app/views/softdrinksindustrylevy/register/complete.scala.html
- app/views/softdrinksindustrylevy/register/contact_details.scala.html
- app/views/softdrinksindustrylevy/register/declaration.scala.html
- app/views/softdrinksindustrylevy/register/identify.scala.html
- app/views/softdrinksindustrylevy/register/litreagePage.scala.html
- app/views/softdrinksindustrylevy/register/organisation_type.scala.html
- app/views/softdrinksindustrylevy/register/partnerships.scala.html
- app/views/softdrinksindustrylevy/register/produce_worldwide.scala.html
- app/views/softdrinksindustrylevy/register/productionSite.scala.html
- app/views/softdrinksindustrylevy/register/radio_button.scala.html
- app/views/softdrinksindustrylevy/register/registration_not_required.scala.html
- app/views/softdrinksindustrylevy/register/secondaryWarehouse.scala.html
- app/views/softdrinksindustrylevy/register/start_date.scala.html
- app/views/softdrinksindustrylevy/register/verify.scala.html
- app/views/softdrinksindustrylevy/variations/business_details.scala.html
- app/views/softdrinksindustrylevy/variations/business_details_summary.scala.html
- app/views/softdrinksindustrylevy/variations/confirmation.scala.html
- app/views/softdrinksindustrylevy/variations/productionSiteWithRef.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary_contact_details.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary_productionSites.scala.html
- app/views/softdrinksindustrylevy/variations/retrieve_summary_secondaryWarehouse.scala.html
- app/views/softdrinksindustrylevy/variations/secondaryWarehouseWithRef.scala.html
- app/views/softdrinksindustrylevy/variations/variations_summary.scala.html
Used the request path to change the page title
Removed the variations flag from contact details
> Changed tab titles on page to use H1 heading on the page

- app/views/uniform/fragments/bigtext.scala.html
- conf/messages
> dereg reason max length

- app/sdil/controllers/VariationsController.scala
- app/views/uniform/fragments/variationsCYA.scala.html
- conf/messages
> cya removed sites

- app/sdil/controllers/ReturnsController.scala
- app/sdil/controllers/SdilWMController.scala
- app/sdil/controllers/VariationsController.scala
- app/sdil/uniform/GDS.scala
- app/sdil/uniform/SdilComponents.scala
- app/views/uniform/address.scala.html
- app/views/uniform/ask.scala.html
- app/views/uniform/bigtext.scala.html
- app/views/uniform/boolean.scala.html
- app/views/uniform/checkboxes.scala.html
- app/views/uniform/contactdetails.scala.html
- app/views/uniform/date.scala.html
- app/views/uniform/journeyEnd.scala.html
- app/views/uniform/literage.scala.html
- app/views/uniform/many.scala.html
- app/views/uniform/radiolist.scala.html
- app/views/uniform/site.scala.html
- app/views/uniform/smallProducer.scala.html
- app/views/uniform/string.scala.html
- app/views/uniform/tell.scala.html
- app/views/uniform/tellTable.scala.html
legends for accessibility, page titles, radioList error message, timezone etc.
and objects not traits - not sure I put everything in the right place here.
please review.
> Sdil 1538 part three

- app/sdil/controllers/SdilWMController.scala
- app/sdil/controllers/VariationsController.scala
- app/views/uniform/fragments/variationsCYA.scala.html
- conf/messages
> min packaging site validation

- app/sdil/config/RegistrationFormDataCache.scala
> Live save4later deserialisation bug

- app/sdil/controllers/VariationsController.scala
- app/views/uniform/fragments/variationsCYA.scala.html
- conf/application.conf
> Sdil 1476 new sites cya

- app/sdil/controllers/SdilWMController.scala
- conf/messages
> re-fixed error message, added page specific heading

- app/views/uniform/fragments/variationsCYA.scala.html
> switched cya page running order

- app/sdil/controllers/SiteRef.scala
> fix for non-numeric siteRef

- app/views/uniform/fragments/variationsCYA.scala.html
> fixed display of activity change and font size on dereg on CYA page

- app/sdil/controllers/SdilWMController.scala
- app/sdil/controllers/VariationsController.scala
> no sites on contactChangeType for voluntary users

- app/views/uniform/fragments/variationsCYA.scala.html
- public/stylesheets/sdil.css
> print link on CYA page

- app/sdil/controllers/VariationsController.scala
> dereg logic in activity variation

- app/sdil/controllers/WarehouseController.scala
> optional trading name fix

- app/views/softdrinksindustrylevy/service_page.scala.html
- conf/app.routes
URI change to avoid collision with defunct returns frontend service
> Returns journey

- app/sdil/controllers/CompleteController.scala
- app/views/uniform/journeyEnd.scala.html
> fix for date formating on journey end page across uniform apps

- test/sdil/controllers/ServicePageControllerSpec.scala
> ignoring NPE tests

- app/sdil/controllers/ReturnsController.scala
> sdilref validation for small producers

- app/views/softdrinksindustrylevy/service_page.scala.html
- app/views/uniform/fragments/returnsCYA.scala.html
- public/javascripts/application.js
> GA event tracking

- app/views/govuk_wrapper.scala.html
> another fix

- public/javascripts/application.js
> fix GA for change links

- app/sdil/config/CommonWiring.scala
- app/sdil/config/ConfigWiring.scala
- app/sdil/connectors/SoftDrinksIndustryLevyConnector.scala
> session caching for retrieved subscriptions

- app/sdil/controllers/RegistrationController.scala
- app/sdil/controllers/SdilWMController.scala
- app/sdil/controllers/VariationsController.scala
- app/sdil/uniform/SdilComponents.scala
- app/views/uniform/ask.scala.html
- app/views/uniform/fragments/registerDeclaration.scala.html
- app/views/uniform/fragments/variationsCYA.scala.html
- app/views/uniform/many.scala.html
- conf/messages
- project/FrontendBuild.scala
- public/stylesheets/sdil.css
Reverts hmrc/soft-drinks-industry-levy-frontend#372 as it breaks the return journey.
> Revert "Sdil 1716 uniform list pattern"

- app/sdil/controllers/RegistrationController.scala
- app/sdil/controllers/SdilWMController.scala
- app/sdil/controllers/VariationsController.scala
- app/sdil/uniform/SdilComponents.scala
- app/views/uniform/ask.scala.html
- app/views/uniform/fragments/registerDeclaration.scala.html
- app/views/uniform/fragments/variationsCYA.scala.html
- app/views/uniform/many.scala.html
- conf/messages
- project/FrontendBuild.scala
- public/stylesheets/sdil.css
Reverts hmrc/soft-drinks-industry-levy-frontend#373
> Reapply "Sdil 1716 uniform list pattern"

- app/sdil/controllers/ServicePageController.scala
- app/views/softdrinksindustrylevy/balance_history.scala.html
- app/views/softdrinksindustrylevy/helpers/howToPay.scala.html
- app/views/softdrinksindustrylevy/service_page.scala.html
- conf/messages
- 'how to pay' section
- padding on balance page
- remove unconfirmed content
- changed 'Date/Time' to just 'Date'
> cosmetic changes

- app/sdil/controllers/ReturnsController.scala
- app/views/uniform/fragments/returnsCYA.scala.html
Stop vol/man users seeing the package own page on returns journey.
> Sdil 1852 vol man

- app/sdil/controllers/RegistrationController.scala
- app/sdil/controllers/SdilWMController.scala
- app/sdil/controllers/VariationsController.scala
- app/sdil/models/Journey.scala
- app/sdil/models/variations/VariationData.scala
- app/sdil/uniform/SdilComponents.scala
and I deleted some TODOs that are out of scope.
> sorted the adjustable returns by return period for which return question

- app/sdil/controllers/VariationsController.scala
- app/sdil/models/variations/VariationData.scala
- app/views/uniform/fragments/returnVariationDifferences.scala.html
- conf/messages
please review in tandem with the backend
> added repayment method

- app/sdil/controllers/RegistrationController.scala
- app/sdil/controllers/ReturnJourney.scala
- app/sdil/controllers/ReturnsController.scala
- app/sdil/controllers/SdilWMController.scala
- app/sdil/controllers/VariationsController.scala
- app/sdil/uniform/SdilComponents.scala
- app/views/uniform/ask.scala.html
- app/views/uniform/cya.scala.html
- app/views/uniform/helpers/backlink.scala.html
- app/views/uniform/many.scala.html
> removed backlinks from the return journey part of return adjustments

- app/sdil/controllers/ReturnJourney.scala
- app/sdil/controllers/SdilWMController.scala
- app/sdil/controllers/ShowBackLink.scala
- app/sdil/controllers/VariationsController.scala
- app/sdil/controllers/package.scala
- app/sdil/uniform/SdilComponents.scala
- app/views/uniform/ask.scala.html
- app/views/uniform/cya.scala.html
- app/views/uniform/many.scala.html
> reinstated backlinks in adjustments small producer sub-journey

- app/sdil/controllers/VariationsController.scala
- conf/app.routes
> clearing down adjustment route

- conf/messages
Reverts hmrc/soft-drinks-industry-levy-frontend#430
> Revert "Ians test" to deploy other more tested code to production.

- conf/messages
Reverts hmrc/soft-drinks-industry-levy-frontend#431
> Revert "Revert "Ians test" to deploy other more tested code to production."

- app/sdil/controllers/SdilWMController.scala
- conf/messages
> fixed small producer validation

- conf/messages
> messages fix

- app/sdil/controllers/ReturnsController.scala
- app/views/uniform/fragments/returnsPaymentsBlurb.scala.html
- conf/messages
- public/stylesheets/sdil.css
> changes to the returns confirmation page

- app/views/uniform/fragments/update_business_addresses.scala.html
- conf/messages
> changed messages up update business addresses page

- conf/messages
> content change on reason for correcting return

- conf/messages
> update copy on returns variation confirmation page

- conf/messages
> changed message when editing contact person

- app/views/softdrinksindustrylevy/helpers/error_summary.scala.html
- app/views/softdrinksindustrylevy/helpers/inputText.scala.html
- app/views/uniform/fragments/bigtext.scala.html
> removed tooltip role attribute from inputText, bigText and error_summary

- app/views/softdrinksindustrylevy/register/verify.scala.html
> no repeat of page title in legend on verify page

- app/views/softdrinksindustrylevy/helpers/addressFields.scala.html
- app/views/softdrinksindustrylevy/helpers/inputText.scala.html
- app/views/softdrinksindustrylevy/helpers/siteFields.scala.html
- app/views/uniform/fragments/address.scala.html
- app/views/uniform/fragments/bigtext.scala.html
- app/views/uniform/fragments/contactdetails.scala.html
- app/views/uniform/fragments/date.scala.html
- app/views/uniform/fragments/packagingSite.scala.html
- app/views/uniform/fragments/site.scala.html
- app/views/uniform/fragments/string.scala.html
- app/views/uniform/fragments/warehouseSite.scala.html
> no maxlength attribute on form input

- app/views/softdrinksindustrylevy/balance_history.scala.html
- conf/messages
> correct page title and date format

- app/views/softdrinksindustrylevy/balance_history.scala.html
- conf/app.routes
- conf/messages
As per the ticket, all of the changes to the transaction history page are implemented.
> Front end changes as mentioned are implemented

- app/views/uniform/helpers/sites_variations_cya.scala.html
- app/views/uniform/many.scala.html
- conf/messages
Replace old URLs on change links for packaging sites
And also changes for 2179 for change link text
> Replace old URLs on change links for packaging sites

- app/views/softdrinksindustrylevy/balance_history.scala.html
The outstanding issue mentioned under 2150 in Pt.8 is now addressed
> Added col scope to the TH tags

- app/sdil/controllers/ReturnJourney.scala
- app/views/uniform/fragments/returnsCYA.scala.html
- app/views/uniform/helpers/sites_variations_cya.scala.html
Removed the usage of null in ReturnJourney controller
> Dls 56 patch

- app/sdil/controllers/ReturnJourney.scala
> DLS-87: Revert of previous code

- build.sbt
play-ui,auth-client version update for soft-drinks-industry-levy-frontend
> DLS-1324 FHDDS tax platform update 

- app/views/softdrinksindustrylevy/balance_history.scala.html
- app/views/softdrinksindustrylevy/helpers/inlineRadioButtonWithConditionalContent.scala.html
- app/views/softdrinksindustrylevy/helpers/radioButtonWithConditionalContent.scala.html
- app/views/uniform/helpers/sites_variations_cya.scala.html
- public/javascripts/application.js
DLS-2158-1 Frontend accessibility changes
> DLS-2158-1 Frontend accessibility changes 

- app/views/uniform/ask.scala.html
- app/views/uniform/fragments/litreage.scala.html
> DLS-2158-4 Tab indices added

- app/views/softdrinksindustrylevy/helpers/error_summary.scala.html
- app/views/uniform/ask.scala.html
- conf/messages
> DLS-2158-5 Tabindex modified

- app/sdil/controllers/ReturnsController.scala
- test/sdil/controllers/ReturnsControllerSpec.scala
Added additional failure scenarios with Logging
> DCWL-3 Added additional failure scenarios with Logging

- app/views/softdrinksindustrylevy/service_page.scala.html
- app/views/uniform/fragments/innerhead.scala.html
- conf/messages
- public/stylesheets/sdil.css
> DLS-4342 Claim Warning messages added

- test/sdil/actions/AuthorisedActionSpec.scala
- test/sdil/actions/RegisteredActionSpec.scala
- test/sdil/controllers/CheckYourAnswersSpec.scala
- test/sdil/controllers/ControllerSpec.scala
- test/sdil/controllers/DirectDebitControllerSpec.scala
- test/sdil/controllers/IdentifyControllerSpec.scala
- test/sdil/controllers/PaymentControllerSpec.scala
- test/sdil/controllers/RegistrationControllerSpec.scala
- test/sdil/controllers/ReturnsControllerSpec.scala
- test/sdil/controllers/ServicePageControllerSpec.scala
- test/sdil/controllers/VariationsControllerSpec.scala
- test/sdil/controllers/VerifyControllerSpec.scala
- test/sdil/forms/FormSpec.scala
- test/sdil/forms/IdentifyFormSpec.scala
- test/sdil/forms/PostcodeMappingSpec.scala
- test/sdil/forms/VerifyFormSpec.scala
- test/sdil/journeys/RegistrationJourneySpec.scala
- test/sdil/journeys/ReturnJourneySpec.scala
- test/sdil/journeys/VariationsJourneySpec.scala
- test/sdil/journeys/package.scala
- test/sdil/models/ReturnSpec.scala
- test/sdil/uniform/GDS.scala
- test/sdil/uniform/SdilComponents.scala
- test/sdil/utils/FakeApplicationSpec.scala
- test/sdil/utils/TestConfig.scala
> Update copyright to2023 (#638)

- app/sdil/actions/AuthorisedAction.scala
- app/sdil/actions/RegisteredAction.scala
- app/sdil/config/AppConfig.scala
- conf/application.conf
- test/sdil/actions/ActionsWithNewServiceEnabledSpec.scala
- test/sdil/controllers/RedirectToNewServiceTests.scala
appConfigs
https://github.com/hmrc/app-config-base/pull/10104
https://github.com/hmrc/app-config-qa/pull/21656
https://github.com/hmrc/app-config-staging/pull/14778
https://github.com/hmrc/app-config-production/pull/21351
> DLS-10121 added config to route to new sdil account frontend
